services:
  postgres:
    image: postgres:17
    container_name: shapegame_postgres
    restart: always
    environment:
      POSTGRES_USER: moonbeam
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shapedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
