services:
  app:
    build: .
    restart: always
    container_name: shapegame
    environment:
      - CONNECTION_STRING=postgres://moonbeam:admin@postgres:5432/shapedb
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    image: postgres:17
    container_name: shapegame_postgres
    restart: always
    environment:
      POSTGRES_USER: moonbeam
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shapedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
